name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Vercel deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add secondary https://D33102:${{ secrets.SECONDARY_REPO_TOKEN }}@github.com/D33102/se2-frontend.git
          git push -f secondary main
